referenceThreshold filter running into an error with the mixed pattern
I am making a commit that gives the error, below.  Now I will try to add print statements and fix the error, because I don't see why this kind of error (list index) would happen.

Traceback (most recent call last):
  File "runfile.py", line 6, in <module>
    MSRESOLVE.main()
  File "C:\Users\fvs\Documents\GitHub\MSRESOLVESG\ExampleTuningCorrectorGasMixture\MSRESOLVE.py", line 5612, in main
    prototypicalReferenceData = PrepareReferenceObjectsAndCorrectionValues(prototypicalReferenceData, ExperimentData.mass_fragment_numbers, ExperimentData,G.extractReferencePatternFromDataOption, G.rpcMoleculesToChange,G.rpcMoleculesToChangeMF,G.rpcTimeRanges)
  File "C:\Users\fvs\Documents\GitHub\MSRESOLVESG\ExampleTuningCorrectorGasMixture\MSRESOLVE.py", line 1686, in PrepareReferenceObjectsAndCorrectionValues
    ReferenceData = ReferenceInputPreProcessing(ReferenceData, verbose) #Note: if implicitSLScorrection is being used, G.currentReferenceDataUnfiltered gets created inside ReferenceInputPreProcessing
  File "C:\Users\fvs\Documents\GitHub\MSRESOLVESG\ExampleTuningCorrectorGasMixture\MSRESOLVE.py", line 1403, in ReferenceInputPreProcessing
    ReferenceData.standardized_reference_patterns = ReferenceThresholdFilter(ReferenceData.standardized_reference_patterns,G.referenceValueThreshold)
  File "C:\Users\fvs\Documents\GitHub\MSRESOLVESG\ExampleTuningCorrectorGasMixture\MSRESOLVE.py", line 630, in ReferenceThresholdFilter
    if referenceDataArray[rowcounter,columncounter] < referenceValueThreshold[columncounter]:
IndexError: list index out of range